// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SeldonStockScannerAPI.Data;

#nullable disable

namespace SeldonStockScannerAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FinvizCompanyEntityWatchListEntity", b =>
                {
                    b.Property<string>("CompaniesTicker")
                        .HasColumnType("nvarchar(12)");

                    b.Property<int>("WatchlistsWatchListId")
                        .HasColumnType("int");

                    b.HasKey("CompaniesTicker", "WatchlistsWatchListId");

                    b.HasIndex("WatchlistsWatchListId");

                    b.ToTable("FinvizCompanyEntityWatchListEntity");
                });

            modelBuilder.Entity("SeldonStockScannerAPI.Models.FinvizCompanyEntity", b =>
                {
                    b.Property<string>("Ticker")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("Change")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Country")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Industry")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MarketCap")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PE")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Price")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Sector")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Volume")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Ticker");

                    b.ToTable("FinvizCompany");
                });

            modelBuilder.Entity("SeldonStockScannerAPI.WatchList.WatchListEntity", b =>
                {
                    b.Property<int>("WatchListId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WatchListId"));

                    b.Property<string>("WatchListName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("WatchListId");

                    b.ToTable("WatchList");
                });

            modelBuilder.Entity("FinvizCompanyEntityWatchListEntity", b =>
                {
                    b.HasOne("SeldonStockScannerAPI.Models.FinvizCompanyEntity", null)
                        .WithMany()
                        .HasForeignKey("CompaniesTicker")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SeldonStockScannerAPI.WatchList.WatchListEntity", null)
                        .WithMany()
                        .HasForeignKey("WatchlistsWatchListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
