// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var finvizCompany = FinvizCompany.FromJson(jsonString);

namespace SeldonStockScannerView.Models
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class FinvizCompany
    {
        [JsonProperty("ticker")]
        public string Ticker { get; set; }

        [JsonProperty("company")]
        public string Company { get; set; }

        [JsonProperty("sector")]
        public string Sector { get; set; }

        [JsonProperty("industry")]
        public string Industry { get; set; }

        [JsonProperty("country")]
        public string Country { get; set; }

        [JsonProperty("marketCap")]
        public string MarketCap { get; set; }

        [JsonProperty("pe")]
        public string Pe { get; set; }

        [JsonProperty("price")]
        public string Price { get; set; }

        [JsonProperty("change")]
        public string Change { get; set; }

        [JsonProperty("volume")]
        public string Volume { get; set; }
    }

    public partial class FinvizCompany
    {
        public static List<FinvizCompany> FromJson(string json) => JsonConvert.DeserializeObject<List<FinvizCompany>>(json, SeldonStockScannerView.Models.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this List<FinvizCompany> self) => JsonConvert.SerializeObject(self, SeldonStockScannerView.Models.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
